// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function disambiguateProductsCategorySelect(input: RequestInfo | URL): RequestInfo | URL {
  const rawUrl =
    typeof input === 'string'
      ? input
      : input instanceof URL
        ? input.toString()
        : input instanceof Request
          ? input.url
          : '';

  if (!rawUrl || !rawUrl.includes('/rest/v1/products')) return input;

  try {
    const url = new URL(rawUrl);
    const select = url.searchParams.get('select');
    if (!select || !select.includes('categories(name)')) return input;

    url.searchParams.set(
      'select',
      select.replace(
        'categories(name)',
        'categories:categories!products_category_id_fkey(name)',
      ),
    );

    if (typeof input === 'string') return url.toString();
    if (input instanceof URL) return url;
    if (input instanceof Request) return new Request(url.toString(), input);
  } catch {
    return input;
  }

  return input;
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const rewrittenInput = disambiguateProductsCategorySelect(input);
    const headers = new Headers(
      typeof Request !== 'undefined' && rewrittenInput instanceof Request ? rewrittenInput.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(rewrittenInput, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
